title: Big Field
theme: just-the-docs
url: https://rafhaels.github.io/bigfield/
logo: bf_logo.png
favicon_ico: 
color_scheme: bigfield
encoding: UTF-8

# Link voltar ao topo
back_to_top: true
back_to_top_text: "Voltar ao topo"

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true


